config/routes.rb
Rock::Application.routes.draw do
  devise_for :users
  namespace 'admin' do
    root :to => "index#index"
    resources :page_categories, :except => [:new, :show, :edit]
    resources :sider_types, :except => [:new, :show, :edit]
    resources :siders, :except => :show
    resources :static_pages, :except => :show
  end
  
  root :to => "static_pages#index"
  ActionDispatch::Routing::Translator.translate_from_file('config','i18n-routes.yml')
  
  # translate_routes does not work with "*" matches, so we do it manually
  match "(:locale)/*url_match" => "static_pages#show", :locale => /en|ru/
  match "*url_match" => "static_pages#show"
end

app/controllers/admin/sider_types_controller.rb
class Admin::SiderTypesController < Admin::IndexController
  def index
    @list_of_all_helpers = SiderType.list_of_all_helpers
  end
  
  def create
    st = SiderType.create :sider_helper_module => params[:sider_helper_module]
    flash[:errors] = st.errors
    redirect_to admin_sider_types_path
  end
  
  def update
    st = SiderType.find params[:id]
    st.update_attribute "enabled",!st.enabled
    flash[:errors] = st.errors
    redirect_to admin_sider_types_path
  end
  
  def destroy
    SiderType.find(params[:id]).destroy
    redirect_to admin_sider_types_path
  end
end

app/helpers/admin/sider_types_helper.rb
module Admin::SiderTypesHelper
end

app/views/admin/sider_types/index.html.erb
<% if flash[:errors] %>
<div id="errorExplanation">
  <h2><%= t.errors.header(flash[:errors].count, SiderType.human_name) %>:</h2>
  <ul>
  <% flash[:errors].full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>
<table class="admin_table">
  <tr>
    <th><%= t.admin.module %></th>
    <th><%= t.admin.description %></th>
    <th><%= t.admin.registration %></th>
    <th><%= t.admin.activity %></th>
  </tr>
<% @list_of_all_helpers.each do |m, h| %>
  <tr>
    <td><%= m %></td>
    <td>
      <% if h[:module] %>
        <%= h[:module].description %>
      <% else %>
        <span class="error"><%= t.admin.absent_module %></span>
      <% end %>
    </td>
    <% if h[:model] %>
      <td><%= t.admin.registered %>
        <%= link_to t.admin.delete_registration, admin_sider_type_path(h[:model]),
              :method => :delete, :confirm => t.admin.delete_registration_confirm %>
      </td>
      <td><%= h[:model].enabled ? t.admin.enabled : t.admin.disabled %>
        <%= link_to t.admin.toggle, admin_sider_type_path(h[:model]), :method => :put %>
      </td>
    <% else %>
      <td><%= link_to t.admin.register, admin_sider_types_path(:sider_helper_module => m),
              :method => :post %></td>
      <td><%= t.admin.register_please %></td>
    <% end %>
  </tr>
<% end %>
</table>