config/routes.rb
Rock::Application.routes.draw do
  devise_for :users
  namespace 'admin' do
    root :to => "index#index"
    resources :page_categories, :except => [:new, :show, :edit]
    resources :sider_types, :except => [:new, :show, :edit]
    resources :siders, :except => :show
    resources :static_pages, :except => :show
  end
  
  root :to => "static_pages#index"
  ActionDispatch::Routing::Translator.translate_from_file('config','i18n-routes.yml')
  
  # translate_routes does not work with "*" matches, so we do it manually
  match "(:locale)/*url_match" => "static_pages#show", :locale => /en|ru/
  match "*url_match" => "static_pages#show"
end

app/models/sider.rb
class Sider < ActiveRecord::Base
  belongs_to :sider_type
  validates_presence_of :title, :sider_position
  before_save :make_dumps
  attr_accessor :params, :restrictions
  after_find :load_dumps
  
  def load_dumps
    self.params = Marshal.load(params_dump)
    self.restrictions = Marshal.load(restrictions_dump)
  end
  
  def make_dumps
    self.params_dump = Marshal.dump(params||{})
    self.restrictions_dump = Marshal.dump(restrictions||{})
  end

  def output_params
    return {} if new_record?
    # title and position is parameters for helper too
    output_params = params.merge :title => title, :sider_position => sider_position
    # if some parameters not asigned, use defaults
    sider_type.helper.default_params.each{ |key, value| output_params[key] ||= value[:value] }
    # sider output params hash
    output_params
  end
end

app/models/sider_type.rb
class SiderType < ActiveRecord::Base
  has_many :siders, :dependent => :destroy
  validates_presence_of :sider_helper_module
  attr_accessor :default_params
  after_find :load_params
  
  # this class method returns hash wIA like
  # :name => {:module => <SiderHelpers::SiderHelper>, :model => <InstanceOfSiderType>}
  def self.list_of_all_helpers
    list = HashWithIndifferentAccess.new{{}}
    Dir[RAILS_ROOT+"/app/helpers/siders/*.rb"].each {|file| require file }
    Siders.constants.each do |sh|
      sh_module = to_helper_module(sh)
      list[sh] = {:module => sh_module} if sh_module.class==Module
    end
    all.each do |st|
      # Hash#merge! not works in this case properly..
      list[st.sider_helper_module] = list[st.sider_helper_module].merge :model => st
    end
    list
  end
  
  # returns sider helper module by simple name or nil if it's not present
  def self.to_helper_module(name)
    eval "Siders::"+name.to_s
  rescue
    nil
  end
  
  def helper
    self.class.to_helper_module sider_helper_module
  end
  
  def load_params
    self.default_params = {}
  end
end

app/controllers/admin/siders_controller.rb
class Admin::SidersController < Admin::IndexController
  def index
    @siders = Sider.includes(:sider_type)
  end
  
  def new
    if params[:sider_type_id] and @sider_type = SiderType.where(:id => params[:sider_type_id] ).first
      @sider = @sider_type.siders.build flash[:sider]
      @sider.params = flash[:params]
      @sider_helper_params = @sider_type.helper.default_params
      @sider_params = @sider.output_params
    else
      @sider_types = SiderType.where :enabled => true
      render "select_sider_type"
    end
  end
  
  def create
    @sider = Sider.create params[:sider]
    @sider.params = params[:params]
    if @sider.save
      redirect_to admin_siders_path
    else
      flash[:sider] = params[:sider]
      flash[:params] = params[:params]
      flash[:errors] = @sider.errors
      redirect_to new_admin_sider_path(:sider_type_id=>params[:sider][:sider_type_id])
    end 
  end
  
  def edit
    @sider = Sider.find params[:id]
    @sider_helper_params = @sider.sider_type.helper.default_params
    @sider_params = @sider.output_params
  end
  
  def update
    @sider = Sider.find(params[:id])
    @sider.params = params[:params]
    if @sider.update_attributes(params[:sider])
      redirect_to admin_siders_path
    else
      flash[:errors] = @sider.errors
      redirect_to edit_admin_sider_path(@sider)
    end 
  end
  
  def destroy
    @sider = Sider.find(params[:id])
    @sider.destroy
    redirect_to admin_siders_path
  end
end

app/helpers/admin/siders_helper.rb
module Admin::SidersHelper
  def param_fields field_name
    result = label :params, field_name
    case @sider_helper_params[field_name][:type]
    when 'check'
      result+= check_box :params, field_name, :checked => (@sider_params[field_name]||@sider_helper_params[field_name][:value])=="1"
    when 'string'
      result+= text_field :params, field_name, :value => @sider_params[field_name]||@sider_helper_params[field_name][:value]
    when 'text'
      result+= text_area :params, field_name, :value => @sider_params[field_name]||@sider_helper_params[field_name][:value], :cols => @sider_helper_params[field_name][:cols]||40, :rows => @sider_helper_params[field_name][:rows]||10
    else
      result+= raw '<span class="right_column">No input for this params type!</span>'
    end
    result
  end
end

app/helpers/siders/auth_siders_helper.rb
module Siders::AuthSidersHelper
  def self.description
    "This sider used for display login/logout form"
  end
  def self.default_params
    { :show_title => {:type => 'check', :value => '1'},
      :greeting_msg => {:type => 'string', :value => 'Hello!'}}
  end
  
  def self.output_method
    :auth_siders_output
  end
end

module ApplicationHelper
  def auth_siders_output(p)
    title = "<h3 class='auth_title'>#{p[:title]}</h3>" if p[:show_title]=='1'
    if user_signed_in?
      form = "<p>#{t.siders.auth.greeting}</p>"
      form+= link_to "Sign out, #{current_user.username}", destroy_user_session_path
    else
      form = capture{form_for("user", :url => user_session_path) do |f|
        concat f.text_field :username 
        concat f.password_field :password
        concat f.check_box :remember_me
        concat f.label :remember_me
        concat f.submit 'Sign in'
        link_to "Forgot your password?", new_password_path('user')
      end}
    end
    <<-HTML
      <div class='sider_#{p[:sider_position]}'>
      #{title}
      <div class='auth_title'>
      #{form}
      </div>
      </div>
    HTML
  end
end

app/helpers/siders/static_siders_helper.rb
module Siders::StaticSidersHelper
  def self.description
    "This sider used for simple display of HTML code"
  end
  def self.default_params
    { :content => {:type => 'text', :cols => 35, :rows => 15, :value => ''},
      :sider_id => {:type => 'string', :value => ''},
      :show_title => {:type => 'check', :value => '1'}}
  end
  
  def self.output_method
    :static_siders_output
  end
end

module ApplicationHelper
  def static_siders_output(p)
    title = "<h3>#{p[:title]}</h3>" if p[:show_title]=='1'
    sider_id = " id='#{p[:sider_id]}'" unless p[:sider_id].blank?
    <<-HTML
      <div#{sider_id} class='sider_#{p[:sider_position]}'>
      #{title}
      <div>#{p[:content]}</div>
      </div>
    HTML
  end
end

app/views/admin/siders/_form.html.erb
<%= form_for [:admin, @sider] do |f| %>
  <% if flash[:errors] %>
  <div id="errorExplanation">
    <h2><%= t.errors.header(flash[:errors].count, Sider.human_name) %>:</h2>
    <ul>
    <% flash[:errors].full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <fieldset class='admin_form'>
    <legend><%= t.admin.general_settings %></legend>
    <span class='left_column'><%= t.admin.type %></span>
    <span class='right_column'><%= @sider.sider_type.sider_helper_module %></span>
    <%= f.hidden_field :sider_type_id %>
    <%= f.label :title %><%= f.text_field :title %>
    <%= f.label :sider_position %><%= f.text_field :sider_position %>
    <%= f.label :display_order %><%= f.text_field :display_order %>
    <%= f.label :access_level %><%= f.text_field :access_level %>
    <%= f.label :enabled %><%= f.check_box :enabled %>
  </fieldset>
  <fieldset class='admin_form'>
    <legend><%= t.admin.sider_params %></legend>
    <% @sider_helper_params.each_key do |p| %>
      <%= param_fields p %>
    <% end %>
  </fieldset>
  <%= f.submit %>
<% end %>

app/views/admin/siders/edit.html.erb
<h2><%= t.admin.edit_sider %></h2>

<%= render 'form' %>

<%= link_to t.admin.back, admin_siders_path %>

app/views/admin/siders/index.html.erb
<h2><%= t.admin["Manage siders"] %></h2>
<%= link_to t.admin.create_new, new_admin_sider_path %>
<table class="admin_table">
  <tr>
    <th>Id</th>
    <th><%= t.admin.title %></th>
    <th><%= t.admin.position %></th>
    <th><%= t.admin.type %></th>
    <th><%= t.admin.activity %></th>
    <th></th>
    <th></th>
  </tr>  
  <% @siders.each do |sider| %>
  <tr>
    <td><%= sider.id %></td>
    <td><%= sider.title %></td>
    <td><%= sider.sider_position %></td>
    <td><%= sider.sider_type.sider_helper_module %>
        <%= " (disabled)" unless sider.sider_type.enabled %>
    </td>
    <td><%= sider.enabled ? "Enabled. " : "Disabled. " %>
      <%= link_to "Toggle activity.", admin_sider_path(sider, :sider => {:enabled => !sider.enabled}), :method => :put %>
    </td>
    <td><%= link_to "Edit", edit_admin_sider_path(sider) %></td>
    <td><%= link_to "Delete", admin_sider_path(sider), :method => :delete, :confirm => "Are you sure?" %></td>
  </tr>
  <% end %>
</table>

app/views/admin/siders/new.html.erb
<h2><%= t.admin.new_sider %></h2>

<%= render 'form' %>

<%= link_to t.admin.back, admin_siders_path %>

app/views/admin/siders/select_sider_type.html.erb
<h2><%= t.admin.select_sider_type %></h2>
<table class="admin_table">
  <tr>
    <th>Id</th>
    <th><%= t.admin.type %></th>
    <th><%= t.admin.description %></th>
    <th></th>
  </tr>  
  <% @sider_types.each do |st| %>
  <tr>
    <td><%= st.id %></td>
    <td><%= st.sider_helper_module %></td>
    <td><%= st.helper.description %></td>
    <td><%= link_to t.admin["Select this type"], new_admin_sider_path(:sider_type_id=>st) %></td>
  </tr>
  <% end %>
</table>