config/routes.rb
Rock::Application.routes.draw do
  devise_for :users
  namespace 'admin' do
    root :to => "index#index"
    resources :page_categories, :except => [:new, :show, :edit]
    resources :sider_types, :except => [:new, :show, :edit]
    resources :siders, :except => :show
    resources :static_pages, :except => :show
  end
  
  root :to => "static_pages#index"
  ActionDispatch::Routing::Translator.translate_from_file('config','i18n-routes.yml')
  
  # translate_routes does not work with "*" matches, so we do it manually
  match "(:locale)/*url_match" => "static_pages#show", :locale => /en|ru/
  match "*url_match" => "static_pages#show"
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  include R18n::Translated
  
  belongs_to :author, :class_name=>"User"
  belongs_to :page_category
  
  validates_presence_of :title
  #TODO validates :url_match
  
  def link locale=nil
    locale ||= I18n.locale
    prefix = locale==I18n.default_locale ? "" : "/#{locale.to_s}"
    prefix + "/" + url_match
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::IndexController
  before_filter :load_categories_graph, :only => [:new, :edit]
  
  def index
    @static_pages = StaticPage.all
  end
  
  def new
    @static_page = StaticPage.create flash[:static_page]
  end
  
  def create
    @static_page = StaticPage.create params[:static_page]
    if @static_page.save
      redirect_to admin_static_pages_path
    else
      flash[:static_page] = params[:static_page]
      flash[:errors] = @static_page.errors
      redirect_to new_admin_static_page_path
    end 
  end
  
  def edit
    @static_page = StaticPage.find params[:id]
  end
  
  def update
    @static_page = StaticPage.find params[:id]
    if @static_page.update_attributes(params[:static_page])
      redirect_to admin_static_pages_path
    else
      flash[:errors] = @static_page.errors
      redirect_to edit_admin_static_page_path(@static_page)
    end 
  end
  
  def destroy
    StaticPage.find(params[:id]).destroy
    redirect_to admin_static_pages_path
  end

private

  def load_categories_graph
    @categories_graph, @categories = {},{}
    PageCategory.all.each do |c|
      @categories_graph.merge! c.id => c.parent_category_id
      @categories.merge! c.id => c
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @current_pages = StaticPage.where("order_on_main > 0").order("order_on_main")
    render :show
  end
  
  def show
    @current_pages = StaticPage.where(:url_match => params[:url_match])
    render :text=>t.static_page.no_matches(params[:url_match]) if @current_pages.empty?
  end
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
  include Admin::PageCategoriesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/static_pages/_form.html.erb
<%= form_for [:admin, @static_page] do |f| %>
  <% if flash[:errors] %>
  <div id="errorExplanation">
    <h2><%= t.errors.header(flash[:errors].count, StaticPage.human_name) %>:</h2>
    <ul>
    <% flash[:errors].full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <fieldset class='admin_form'>
    <legend><%= t.admin.general_settings %></legend>
    <%= f.label :url_match %><%= f.text_field :url_match %>
    <%= f.label :title %><%= f.text_field :title %>
    <%= f.label :show_title %><%= f.check_box :show_title %>
    <%= f.label :page_category_id %>
    <%= f.select :page_category_id, [["root", nil]]+draw_options_tree %>
    <%= f.label :content %><%= f.text_area :content %>
    <%= f.label :access_level %><%= f.text_field :access_level %>
  </fieldset>
  <%= f.submit %>
<% end %>

app/views/admin/static_pages/edit.html.erb
<h2><%= t.admin.edit_static_page %></h2>

<%= render 'form' %>

<%= link_to t.admin.back, admin_static_pages_path %>

app/views/admin/static_pages/index.html.erb
<h2><%= t.admin["Manage static pages"] %></h2>
<%= link_to t.admin.create_new, new_admin_static_page_path %>
<table class="admin_table">
  <tr>
    <th>Id</th>
    <th><%= t.admin.title %></th>
    <th>URL</th>
    <th></th>
    <th></th>
  </tr>  
  <% @static_pages.each do |page| %>
  <tr>
    <td><%= page.id %></td>
    <td><%= page.title %></td>
    <td><%= page.url_match %></td>
    <td><%= link_to "Edit", edit_admin_static_page_path(page) %></td>
    <td><%= link_to "Delete", admin_static_page_path(page), :method => :delete, :confirm => "Are you sure?" %></td>
  </tr>
  <% end %>
</table>

app/views/admin/static_pages/new.html.erb
<h2><%= t.admin.new_static_page %></h2>

<%= render 'form' %>

<%= link_to t.admin.back, admin_static_pages_path %>