config/routes.rb
Rock::Application.routes.draw do
  devise_for :users
  namespace 'admin' do
    root :to => "index#index"
    resources :page_categories, :except => [:new, :show, :edit]
    resources :sider_types, :except => [:new, :show, :edit]
    resources :siders, :except => :show
    resources :static_pages, :except => :show
  end
  
  root :to => "static_pages#index"
  ActionDispatch::Routing::Translator.translate_from_file('config','i18n-routes.yml')
  
  # translate_routes does not work with "*" matches, so we do it manually
  match "(:locale)/*url_match" => "static_pages#show", :locale => /en|ru/
  match "*url_match" => "static_pages#show"
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rock - <%= t.admin.admin_zone %></title>
  <%= stylesheet_link_tag 'admin' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p><%= link_to t.admin["Back to site"], root_path %></p>
  <% if user_signed_in? %>
    <p><%= link_to t.devise.sign_out(current_user.username),
           destroy_user_session_path(:admin_zone=>true) %></p>
    <p>
      <%= link_to t.admin["Main panel"], admin_root_path %>
      <%= link_to t.admin["Manage static pages"], admin_static_pages_path %>
      <%= link_to t.admin["Manage categories"], admin_page_categories_path %>
      <%= link_to t.admin["Register siders"], admin_sider_types_path %>
      <%= link_to t.admin["Manage siders"], admin_siders_path %>
    </p>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rock</title>
  <%= stylesheet_link_tag 'layout' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="top">
    <%= sider 'top' %>
  </div>
  <div id="left"><%= sider 'left' %></div>
  <div id="right"><%= sider 'right' %></div>
  <div id="content"><%= yield %></div>
  <div class="clr"></div>
  <div id="bottom"><%= sider 'bottom' %></div>
</body>
</html>